//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 12:42:00 PM CST 
//


package com.eshare.zkcfg.webservice.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb.cimb.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TransactionID_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "TransactionID");
    private final static QName _ChannelID_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "ChannelID");
    private final static QName _TerminalID_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "TerminalID");
    private final static QName _TransactionDate_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "TransactionDate");
    private final static QName _CompanyCode_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "CompanyCode");
    private final static QName _CustomerKey1_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "CustomerKey1");
    private final static QName _CustomerKey2_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "CustomerKey2");
    private final static QName _CustomerKey3_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "CustomerKey3");
    private final static QName _AdditionalData1_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "AdditionalData1");
    private final static QName _AdditionalData2_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "AdditionalData2");
    private final static QName _AdditionalData3_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "AdditionalData3");
    private final static QName _AdditionalData4_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "AdditionalData4");
    private final static QName _BillCurrency_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "BillCurrency");
    private final static QName _BillCode_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "BillCode");
    private final static QName _BillAmount_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "BillAmount");
    private final static QName _BillReference_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "BillReference");
    private final static QName _Currency_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "Currency");
    private final static QName _Amount_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "Amount");
    private final static QName _Fee_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "Fee");
    private final static QName _PaidAmount_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "PaidAmount");
    private final static QName _CustomerName_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "CustomerName");
    private final static QName _FlagPayment_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "FlagPayment");
    private final static QName _ResponseCode_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "ResponseCode");
    private final static QName _ResponseDescription_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "ResponseDescription");
    private final static QName _Language_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "Language");
    private final static QName _ReferenceNumberTransaction_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "ReferenceNumberTransaction");
    private final static QName _FlagPaymentList_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "FlagPaymentList");
    private final static QName _PaymentFlag_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "PaymentFlag");
    private final static QName _EchoRequest_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "EchoRequest");
    private final static QName _EchoResponse_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "EchoResponse");
    private final static QName _CIMB3RdPartyInquiryRq_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "CIMB3rdParty_InquiryRq");
    private final static QName _CIMB3RdPartyInquiryRs_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "CIMB3rdParty_InquiryRs");
    private final static QName _CIMB3RdPartyPaymentRq_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "CIMB3rdParty_PaymentRq");
    private final static QName _CIMB3RdPartyPaymentRs_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "CIMB3rdParty_PaymentRs");
    private final static QName _InquiryRq_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "InquiryRq");
    private final static QName _InquiryRs_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "InquiryRs");
    private final static QName _PaymentRq_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "PaymentRq");
    private final static QName _PaymentRs_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "PaymentRs");
    private final static QName _BillDetail_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "BillDetail");
    private final static QName _BillDetailList_QNAME = new QName("http://CIMB3rdParty/BillPaymentWS", "BillDetailList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb.cimb.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CIMB3RdPartyInquiryRq }
     * 
     */
    public CIMB3RdPartyInquiryRq createCIMB3RdPartyInquiryRq() {
        return new CIMB3RdPartyInquiryRq();
    }

    /**
     * Create an instance of {@link CIMB3RdPartyInquiryRs }
     * 
     */
    public CIMB3RdPartyInquiryRs createCIMB3RdPartyInquiryRs() {
        return new CIMB3RdPartyInquiryRs();
    }

    /**
     * Create an instance of {@link CIMB3RdPartyPaymentRq }
     * 
     */
    public CIMB3RdPartyPaymentRq createCIMB3RdPartyPaymentRq() {
        return new CIMB3RdPartyPaymentRq();
    }

    /**
     * Create an instance of {@link CIMB3RdPartyPaymentRs }
     * 
     */
    public CIMB3RdPartyPaymentRs createCIMB3RdPartyPaymentRs() {
        return new CIMB3RdPartyPaymentRs();
    }

    /**
     * Create an instance of {@link InquiryRq }
     * 
     */
    public InquiryRq createInquiryRq() {
        return new InquiryRq();
    }

    /**
     * Create an instance of {@link InquiryRs }
     * 
     */
    public InquiryRs createInquiryRs() {
        return new InquiryRs();
    }

    /**
     * Create an instance of {@link PaymentRq }
     * 
     */
    public PaymentRq createPaymentRq() {
        return new PaymentRq();
    }

    /**
     * Create an instance of {@link PaymentRs }
     * 
     */
    public PaymentRs createPaymentRs() {
        return new PaymentRs();
    }

    /**
     * Create an instance of {@link BillDetail }
     * 
     */
    public BillDetail createBillDetail() {
        return new BillDetail();
    }

    /**
     * Create an instance of {@link ArrayOfBillDetail }
     * 
     */
    public ArrayOfBillDetail createArrayOfBillDetail() {
        return new ArrayOfBillDetail();
    }

    /**
     * Create an instance of {@link CIMB3RdPartyEchoRq }
     * 
     */
    public CIMB3RdPartyEchoRq createCIMB3RdPartyEchoRq() {
        return new CIMB3RdPartyEchoRq();
    }

    /**
     * Create an instance of {@link CIMB3RdPartyEchoRs }
     * 
     */
    public CIMB3RdPartyEchoRs createCIMB3RdPartyEchoRs() {
        return new CIMB3RdPartyEchoRs();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "TransactionID")
    public JAXBElement<String> createTransactionID(String value) {
        return new JAXBElement<String>(_TransactionID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "ChannelID")
    public JAXBElement<String> createChannelID(String value) {
        return new JAXBElement<String>(_ChannelID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "TerminalID")
    public JAXBElement<String> createTerminalID(String value) {
        return new JAXBElement<String>(_TerminalID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "TransactionDate")
    public JAXBElement<String> createTransactionDate(String value) {
        return new JAXBElement<String>(_TransactionDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "CompanyCode")
    public JAXBElement<String> createCompanyCode(String value) {
        return new JAXBElement<String>(_CompanyCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "CustomerKey1")
    public JAXBElement<String> createCustomerKey1(String value) {
        return new JAXBElement<String>(_CustomerKey1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "CustomerKey2")
    public JAXBElement<String> createCustomerKey2(String value) {
        return new JAXBElement<String>(_CustomerKey2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "CustomerKey3")
    public JAXBElement<String> createCustomerKey3(String value) {
        return new JAXBElement<String>(_CustomerKey3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "AdditionalData1")
    public JAXBElement<String> createAdditionalData1(String value) {
        return new JAXBElement<String>(_AdditionalData1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "AdditionalData2")
    public JAXBElement<String> createAdditionalData2(String value) {
        return new JAXBElement<String>(_AdditionalData2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "AdditionalData3")
    public JAXBElement<String> createAdditionalData3(String value) {
        return new JAXBElement<String>(_AdditionalData3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "AdditionalData4")
    public JAXBElement<String> createAdditionalData4(String value) {
        return new JAXBElement<String>(_AdditionalData4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "BillCurrency")
    public JAXBElement<String> createBillCurrency(String value) {
        return new JAXBElement<String>(_BillCurrency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "BillCode")
    public JAXBElement<String> createBillCode(String value) {
        return new JAXBElement<String>(_BillCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "BillAmount")
    public JAXBElement<Integer> createBillAmount(Integer value) {
        return new JAXBElement<Integer>(_BillAmount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "BillReference")
    public JAXBElement<String> createBillReference(String value) {
        return new JAXBElement<String>(_BillReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "Currency")
    public JAXBElement<String> createCurrency(String value) {
        return new JAXBElement<String>(_Currency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "Amount")
    public JAXBElement<Integer> createAmount(Integer value) {
        return new JAXBElement<Integer>(_Amount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "Fee")
    public JAXBElement<Integer> createFee(Integer value) {
        return new JAXBElement<Integer>(_Fee_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "PaidAmount")
    public JAXBElement<Integer> createPaidAmount(Integer value) {
        return new JAXBElement<Integer>(_PaidAmount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "CustomerName")
    public JAXBElement<String> createCustomerName(String value) {
        return new JAXBElement<String>(_CustomerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "FlagPayment")
    public JAXBElement<String> createFlagPayment(String value) {
        return new JAXBElement<String>(_FlagPayment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "ResponseCode")
    public JAXBElement<String> createResponseCode(String value) {
        return new JAXBElement<String>(_ResponseCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "ResponseDescription")
    public JAXBElement<String> createResponseDescription(String value) {
        return new JAXBElement<String>(_ResponseDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "Language")
    public JAXBElement<String> createLanguage(String value) {
        return new JAXBElement<String>(_Language_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "ReferenceNumberTransaction")
    public JAXBElement<String> createReferenceNumberTransaction(String value) {
        return new JAXBElement<String>(_ReferenceNumberTransaction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "FlagPaymentList")
    public JAXBElement<String> createFlagPaymentList(String value) {
        return new JAXBElement<String>(_FlagPaymentList_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "PaymentFlag")
    public JAXBElement<String> createPaymentFlag(String value) {
        return new JAXBElement<String>(_PaymentFlag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "EchoRequest")
    public JAXBElement<String> createEchoRequest(String value) {
        return new JAXBElement<String>(_EchoRequest_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "EchoResponse")
    public JAXBElement<String> createEchoResponse(String value) {
        return new JAXBElement<String>(_EchoResponse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIMB3RdPartyInquiryRq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "CIMB3rdParty_InquiryRq")
    public JAXBElement<CIMB3RdPartyInquiryRq> createCIMB3RdPartyInquiryRq(CIMB3RdPartyInquiryRq value) {
        return new JAXBElement<CIMB3RdPartyInquiryRq>(_CIMB3RdPartyInquiryRq_QNAME, CIMB3RdPartyInquiryRq.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIMB3RdPartyInquiryRs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "CIMB3rdParty_InquiryRs")
    public JAXBElement<CIMB3RdPartyInquiryRs> createCIMB3RdPartyInquiryRs(CIMB3RdPartyInquiryRs value) {
        return new JAXBElement<CIMB3RdPartyInquiryRs>(_CIMB3RdPartyInquiryRs_QNAME, CIMB3RdPartyInquiryRs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIMB3RdPartyPaymentRq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "CIMB3rdParty_PaymentRq")
    public JAXBElement<CIMB3RdPartyPaymentRq> createCIMB3RdPartyPaymentRq(CIMB3RdPartyPaymentRq value) {
        return new JAXBElement<CIMB3RdPartyPaymentRq>(_CIMB3RdPartyPaymentRq_QNAME, CIMB3RdPartyPaymentRq.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIMB3RdPartyPaymentRs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "CIMB3rdParty_PaymentRs")
    public JAXBElement<CIMB3RdPartyPaymentRs> createCIMB3RdPartyPaymentRs(CIMB3RdPartyPaymentRs value) {
        return new JAXBElement<CIMB3RdPartyPaymentRs>(_CIMB3RdPartyPaymentRs_QNAME, CIMB3RdPartyPaymentRs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InquiryRq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "InquiryRq")
    public JAXBElement<InquiryRq> createInquiryRq(InquiryRq value) {
        return new JAXBElement<InquiryRq>(_InquiryRq_QNAME, InquiryRq.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InquiryRs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "InquiryRs")
    public JAXBElement<InquiryRs> createInquiryRs(InquiryRs value) {
        return new JAXBElement<InquiryRs>(_InquiryRs_QNAME, InquiryRs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaymentRq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "PaymentRq")
    public JAXBElement<PaymentRq> createPaymentRq(PaymentRq value) {
        return new JAXBElement<PaymentRq>(_PaymentRq_QNAME, PaymentRq.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaymentRs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "PaymentRs")
    public JAXBElement<PaymentRs> createPaymentRs(PaymentRs value) {
        return new JAXBElement<PaymentRs>(_PaymentRs_QNAME, PaymentRs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BillDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "BillDetail")
    public JAXBElement<BillDetail> createBillDetail(BillDetail value) {
        return new JAXBElement<BillDetail>(_BillDetail_QNAME, BillDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfBillDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://CIMB3rdParty/BillPaymentWS", name = "BillDetailList")
    public JAXBElement<ArrayOfBillDetail> createBillDetailList(ArrayOfBillDetail value) {
        return new JAXBElement<ArrayOfBillDetail>(_BillDetailList_QNAME, ArrayOfBillDetail.class, null, value);
    }

}
